[project]
name = ""
version = ""
description = ""
authors = [
    {name = "svtter", email = "svtter@qq.com"},
]
dependencies = [
    "sanic>=22.6.2",
]
requires-python = ">=3.9"
license = {text = "MIT"}

[tool.pdm]

[build-system]
requires = ["pdm-pep517>=0.12.0"]
build-backend = "pdm.pep517.api"
